SPORTS = [
    "Swimming",
    "Running",
    "Cycling",
    "Football",
    "Basketball",
    "Tennis",
    "Volleyball",
    "Badminton",
    "Table Tennis",
    "Golf",
    "Boxing",
    "Martial Arts",
    "Yoga",
    "Pilates",
    "Weightlifting",
    "CrossFit",
    "Rowing",
    "Skiing",
    "Snowboarding",
    "Surfing",
    "Rock Climbing",
    "Hiking",
    "Dance",
    "Gymnastics",
    "Squash",
    "Other"
]